import type { Program, Session, CalendarEvent, CohortMember } from './types';

export const programs: Program[] = [
  {
    id: 'ib-analyst',
    title: 'Investment Banking Analyst Immersion',
    category: 'Finance',
    description: 'Build confidence in financial modelling and learn how analysts think through live deal situations.',
    coach: 'Maya Thompson',
    coachInitials: 'MT',
    duration: '4 weeks',
    sessions: 4,
    enrolled: 16,
    capacity: 20,
    color: 'blue',
    status: 'Published',
    difficulty: 'Intermediate',
  },
  {
    id: 'product-case',
    title: 'Product Manager Case Practice',
    category: 'Product',
    description: 'Practice the product sense, analytics and communication skills that hiring teams look for.',
    coach: 'Sofia Lange',
    coachInitials: 'SL',
    duration: '3 weeks',
    sessions: 3,
    enrolled: 14,
    capacity: 20,
    color: 'orange',
    status: 'Published',
    difficulty: 'Intermediate',
  },
  {
    id: 'data-bootcamp',
    title: 'Data Analyst Bootcamp',
    category: 'Data',
    description: 'Turn messy business questions into clear analysis, useful insights and confident recommendations.',
    coach: 'Ravi Kapoor',
    coachInitials: 'RK',
    duration: '2 weeks',
    sessions: 4,
    enrolled: 14,
    capacity: 16,
    color: 'green',
    status: 'Published',
    difficulty: 'Beginner',
  },
  {
    id: 'risk-immersion',
    title: 'Quantitative Risk Analyst Immersion',
    category: 'Finance',
    description: 'Explore risk frameworks and build a practical point of view through guided case work.',
    coach: 'Daniel Eyo',
    coachInitials: 'DE',
    duration: '4 weeks',
    sessions: 4,
    enrolled: 20,
    capacity: 20,
    color: 'red',
    status: 'Published',
    difficulty: 'Advanced',
  },
  {
    id: 'consulting-case',
    title: 'Strategy Consulting Case Program',
    category: 'Consulting',
    description: 'Crack ambiguous business problems using structured consulting frameworks and live case practice.',
    coach: 'Amara Bello',
    coachInitials: 'AB',
    duration: '3 weeks',
    sessions: 3,
    enrolled: 9,
    capacity: 16,
    color: 'orange',
    status: 'Published',
    difficulty: 'Intermediate',
  },
  {
    id: 'swe-interview',
    title: 'Software Engineering Interview Simulation',
    category: 'Software Engineering',
    description: 'Sharpen your system design and coding interview skills through realistic mock interviews with engineers.',
    coach: 'Julien Petit',
    coachInitials: 'JP',
    duration: '3 weeks',
    sessions: 4,
    enrolled: 11,
    capacity: 20,
    color: 'blue',
    status: 'Published',
    difficulty: 'Advanced',
  },
];

export const upcomingSessions: Session[] = [
  { id: 's1', title: 'Introduction to business problem framing', program: 'Data Analyst Bootcamp', date: 'Today', time: '10:00 – 10:45', type: 'Workshop' },
  { id: 's2', title: 'Building a compelling case narrative', program: 'Product Manager Case Practice', date: 'Tomorrow', time: '14:00 – 14:45', type: 'Case study' },
  { id: 's3', title: 'Feedback & career discussion', program: 'Investment Banking Analyst', date: 'Thu, 18 Apr', time: '16:30 – 17:15', type: 'Feedback' },
];

export const calendarEvents: CalendarEvent[] = [
  { id: 'c1', day: 3, title: 'Financial modelling basics', program: 'IB Analyst', time: '10:00', color: 'blue' },
  { id: 'c2', day: 7, title: 'Product sense workshop', program: 'Product Case', time: '14:00', color: 'orange' },
  { id: 'c3', day: 10, title: 'Data cleaning lab', program: 'Data Bootcamp', time: '10:00', color: 'green' },
  { id: 'c4', day: 14, title: 'Valuation deep dive', program: 'IB Analyst', time: '16:00', color: 'blue' },
  { id: 'c5', day: 16, title: 'Problem framing intro', program: 'Data Bootcamp', time: '10:00', color: 'green' },
  { id: 'c6', day: 17, title: 'Case narrative building', program: 'Product Case', time: '14:00', color: 'orange' },
  { id: 'c7', day: 18, title: 'Feedback & career', program: 'IB Analyst', time: '16:30', color: 'blue' },
  { id: 'c8', day: 21, title: 'Risk frameworks', program: 'Risk Immersion', time: '11:00', color: 'red' },
  { id: 'c9', day: 24, title: 'Analytics storytelling', program: 'Data Bootcamp', time: '13:00', color: 'green' },
  { id: 'c10', day: 25, title: 'Mock case interview', program: 'Product Case', time: '15:00', color: 'orange' },
  { id: 'c11', day: 28, title: 'Portfolio review', program: 'Risk Immersion', time: '10:00', color: 'red' },
];

export const cohortMembers: CohortMember[] = [
  { id: 'm1', name: 'Alex Carter', initials: 'AC', email: 'alex.carter@email.com', progress: 65, status: 'On track', avatarColor: 'green' },
  { id: 'm2', name: 'Priya Sharma', initials: 'PS', email: 'priya.sharma@email.com', progress: 80, status: 'On track', avatarColor: 'purple' },
  { id: 'm3', name: 'Marcus Chen', initials: 'MC', email: 'marcus.chen@email.com', progress: 40, status: 'Behind', avatarColor: 'blue' },
  { id: 'm4', name: 'Sofia Rodriguez', initials: 'SR', email: 'sofia.rodriguez@email.com', progress: 100, status: 'Completed', avatarColor: 'orange' },
  { id: 'm5', name: 'James Okafor', initials: 'JO', email: 'james.okafor@email.com', progress: 55, status: 'On track', avatarColor: 'green' },
  { id: 'm6', name: 'Yuki Tanaka', initials: 'YT', email: 'yuki.tanaka@email.com', progress: 30, status: 'Behind', avatarColor: 'blue' },
];

export const faqs = [
  { id: 'f1', question: 'How do I join a program?', answer: 'Browse the Explore programs page, find a program that fits your goals, and click "Join open cohort." You will receive a confirmation and your first session will appear on your calendar.' },
  { id: 'f2', question: 'Can I switch between student, coach, and admin views?', answer: 'Yes. Use the role switcher in the sidebar to preview how the platform looks from each perspective. Your actual permissions are tied to your account.' },
  { id: 'f3', question: 'What happens if I miss a session?', answer: 'All sessions are recorded and available in your program materials. You can catch up anytime, but we recommend attending live for the best experience.' },
  { id: 'f4', question: 'How do I contact my coach?', answer: 'Go to My Programs, open the program, and you will find your coach\'s contact details and preferred communication channel on the cohort page.' },
  { id: 'f5', question: 'Can I get a refund?', answer: 'If you withdraw within the first week of a program, you are eligible for a full refund. Contact support through the Help Center for assistance.' },
];
